source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'FinalFrontier' do
# [START base_dependencies]
pod 'Firebase/Core'
pod 'Firebase/Analytics'
# pod 'Firebase/MLVision'
# [END base_dependencies]
# pod 'Firebase/MLVisionAutoML'
# pod 'Firebase/MLVisionObjectDetection'
# pod 'Firebase/MLVisionBarcodeModel'
# pod 'Firebase/MLVisionFaceModel'
# pod 'Firebase/MLVisionLabelModel'
# pod 'Firebase/MLVisionTextModel'
# If using an on-device API:
# pod 'Firebase/MLVisionTextModel'
end
